config/routes.rb
Rails.application.routes.draw do

  # トップページ
  root to: 'home#index'
  # アバウトページ
  get 'home/about'
  # ユーザ選択ページ
  get 'home/choice'
  get 'home/choice_login'

    # 一般ユーザー
  devise_for :general_users, controllers: {
    sessions: 'general_users/sessions',
    passwords: 'general_users/passwords',
    registrations: 'general_users/registrations'
  }

  # 農家ユーザー
  devise_for :farmer_users, controllers: {
    sessions: 'farmer_users/sessions',
    passwords: 'farmer_users/passwords',
    registrations: 'farmer_users/registrations'
  }



# 一般ユーザー
  namespace :general_users do
    resources :customers, only: [:show]
    resource :users, only: [:show, :edit, :update] do
    collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
    #joinは、イベントに対して参加フォームを送信する。joinは、に結びつくためネスト（親子関係）する
    resources :events, only: [:index, :show] do
       get 'search', on: :collection
      resources :joins, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        post 'back'
        get 'complete'

      end
    end
  end

  #コメントは、投稿画像に対してコメントされる。post_commentsは、postに結びつくためネスト（親子関係）する
    resources :posts, only: [:index, :show] do
     resources :post_comments, only: [:create, :destroy]
    end

  end

  #農家ユーザー
  namespace :farmer_users do
    resources :customers, only: [:show]

    resource :users, only: [:show, :edit, :update] do
    collection do
      get 'unsubscribe'
      patch 'withdraw'
      end
    end

    #joinは、イベントに対して参加フォームを送信する。joinは、に結びつくためネスト（親子関係）する
    resources :events, only: [:new, :create, :index, :show, :destroy] do
      get 'search', on: :collection

      collection do
        get 'confirm'
      # post 'update'
      end
     resources :joins, only: [:new, :create, :index] do
     # 7つ以外のアクションがある時は，collection(idなし)とmember(id含む)を使って指定する。
      collection do
        post 'confirm'
        post 'back'
        get 'complete'
        # get 'show'
        end
      end
   end

    #コメントは、投稿画像に対してコメントする。このため、post_commentsは、postに結びつくためネスト（親子関係）する
    resources :posts, only: [:create, :index, :show, :destroy] do
     resources :post_comments, only: [:create, :destroy]
    end


  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/general_user.rb
class GeneralUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         validates :name, presence: true
        # has_many :posts, dependent: :destroy

         # Post_commentモデルと関連づける
         has_many :post_comments, dependent: :destroy

         has_many :joins, dependent: :destroy

         # refileを使って、画像投稿ができるようにする
           attachment :profile_image

end

app/controllers/farmer_users/users_controller.rb
class FarmerUsers::UsersController < ApplicationController
  before_action :authenticate_farmer_user!

  def show
    @farmer_user = current_farmer_user
    @posts = @farmer_user.posts.all.order(created_at: :desc)
    @events = @farmer_user.events.all.order(created_at: :desc)
    @joins = @farmer_user.joins.all.order(created_at: :desc)
    @join_lists = Join.all.order(created_at: :desc)
    @event_lists = @farmer_user.events.all.order(created_at: :desc)

  end

  def edit
    @farmer_user = current_farmer_user
  end

  def update
    @farmer_user = current_farmer_user
    if @farmer_user.update(farmer_user_params)
      flash[:notice] = '情報を変更しました。'
      redirect_to farmer_users_users_path(current_farmer_user)
    else
      render :edit
    end
  end

  def statusupdate
    # if @event.update(event_params)
  #     redirect_to confirm_farmer_users_events, notice: "対応ステータスを更新しました"
  # else
  #     render :confirm, alert: "対応ステータスを更新できませんでした"
  # end

  end

  # 退会ページ
  def unsubscribe
     @farmer_user = current_farmer_user
  end

  def withdraw
    @farmer_user = current_farmer_user
    @farmer_user.destroy
    flash[:notice] = "ありがとうございました。又のご利用を心よりお待ちしております。"
    redirect_to root_path
  end

   def farmer_user_params
     	params.require(:farmer_user).permit(:name, :email, :profile_image)
   end
end

app/controllers/general_users/confirmations_controller.rb
# frozen_string_literal: true

class GeneralUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/general_users/customers_controller.rb
class GeneralUsers::CustomersController < ApplicationController
before_action :authenticate_general_user!
  def show
    @farmer_user = FarmerUser.find(params[:id])
    @posts = @farmer_user.posts.all.order(created_at: :desc)
    @events = @farmer_user.events.all.order(created_at: :desc)
  end

end

app/controllers/general_users/events_controller.rb
class GeneralUsers::EventsController < ApplicationController
  before_action :authenticate_general_user!
  def index
    @events = Event.all.order(created_at: :desc)
  end

  def show
    @event = Event.find(params[:id])
  end

  def search
    @events = Event.search(params[:keyword])
    @keyword = params[:keyword]
    render "index"
  end

end

app/controllers/general_users/joins_controller.rb
class GeneralUsers::JoinsController < ApplicationController
before_action :authenticate_general_user!
  def new
    @event = Event.find(params[:event_id])
    @join = Join.new
  end

   # newアクションから入力内容を受け取り、
   # 送信ボタンを押されたらcreateアクションを実行します
  def confirm
    @event = Event.find(params[:event_id])
    @join = Join.new(join_params)
    @join.general_user_id = current_general_user.id
  end

  # 入力内容に誤りがあった場合
  def back
    @event = Event.find(params[:event_id])
    @join = Join.new(join_params)
    render :new
  end

  def create
     @event = Event.find(params[:event_id])
     @join = current_general_user.joins.new(join_params)
     @join.event_id = @event.id
    if @join.save
     redirect_to complete_general_users_event_joins_path
    else
     render :new
    end
  end

  def complete
  end

  def index
    @general_user = current_general_user
    @joins = @general_user.joins.all.order(created_at: :desc)
  end

  # def show
  # @join = Join.find(params[:join_id])
  # end

  private

  def join_params
    params.require(:join).permit(:general_user_id, :event_id, :email, :phone, :people, :name, :memo)
  end

end

app/controllers/general_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class GeneralUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/general_users/passwords_controller.rb
# frozen_string_literal: true

class GeneralUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/general_users/post_comments_controller.rb
class GeneralUsers::PostCommentsController < ApplicationController
  

  def create
    post = Post.find(params[:post_id])
    # comment = current_general_user.post_comments.new(post_comment_params)
    comment = PostComment.new(post_comment_params)
    if current_general_user
    comment.general_user_id = current_general_user.id
    else
    comment.farmer_user_id = current_farmer_user.id
    end
    comment.post_id = post.id
    comment.save
    redirect_to general_users_post_path(params[:post_id])
  end
  def destroy
    PostComment.find_by(id: params[:id]).destroy
    redirect_to general_users_post_path(params[:post_id])
  end

  private
  def post_comment_params
  params.require(:post_comment).permit(:comment)
  end

end

app/controllers/general_users/posts_controller.rb
class GeneralUsers::PostsController < ApplicationController

  before_action :authenticate_general_user!
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show

    @post = Post.find(params[:id])
    @post_comment = PostComment.new #コメントのインスタンス変数を記述
  end

end

app/controllers/general_users/registrations_controller.rb
# frozen_string_literal: true

class GeneralUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/general_users/sessions_controller.rb
# frozen_string_literal: true

class GeneralUsers::SessionsController < Devise::SessionsController
  before_action :reject_general_user, only: [:create]

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected
   def reject_general_user
    @general_user = GeneralUser.find_by(email: params[:general_user][:email].downcase)
    if @general_user
     if (@general_user.valid_password?(params[:general_user][:password]) && !@general_user.is_active)
      flash[:error] = "退会済みです。新たにアカウントを作成してください。"
      redirect_to new_general_user_registration_path
     else
      flash[:error] = "必須項目を入力してください。"
     end
    end
   end
end

app/controllers/general_users/unlocks_controller.rb
# frozen_string_literal: true

class GeneralUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/general_users/users_controller.rb
class GeneralUsers::UsersController < ApplicationController
   before_action :authenticate_general_user!

  def show
    @general_user = current_general_user
    @joins = @general_user.joins.all.order(created_at: :desc)
  end

  def edit
    @general_user = current_general_user
  end

  def update
    @general_user = current_general_user
    if @general_user.update(general_user_params)
      flash[:notice] = '情報を変更しました。'
      redirect_to general_users_users_path(current_general_user)
    else
      render :edit
    end
  end

   # 退会ページ
  def unsubscribe
     @general_user = current_general_user
  end

  def withdraw
    @general_user = current_general_user
    # @general_user.update(is_active: false)# //is_deletedをtrueへ
    @general_user.destroy
    flash[:notice] = "ありがとうございました。又のご利用を心よりお待ちしております。"
    redirect_to root_path
  end




   def general_user_params
     	params.require(:general_user).permit(:name, :email, :profile_image)
   end
end

app/helpers/farmer_users/users_helper.rb
module FarmerUsers::UsersHelper
end

app/helpers/general_users/customers_helper.rb
module GeneralUsers::CustomersHelper
end

app/helpers/general_users/events_helper.rb
module GeneralUsers::EventsHelper
end

app/helpers/general_users/joins_helper.rb
module GeneralUsers::JoinsHelper
end

app/helpers/general_users/post_comments_helper.rb
module GeneralUsers::PostCommentsHelper
end

app/helpers/general_users/posts_helper.rb
module GeneralUsers::PostsHelper
end

app/views/general_users/users/edit.html.erb
<div class="container">
 <%= form_with model:@general_user, url:general_users_users_path, local:true do |f| %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>プロフィール編集</h2>

        <div class="form-group">

          <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"ニックネーム" %>
        </div>
         <%= attachment_image_tag @general_user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
       　<%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>

        <div class="form-group">
          <%= f.text_field :email, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"メールアドレス" %>
        </div>

        <div class="form-group">
          <%= f.submit "保存", class:"btn btn-primary" %>
        </div>
    </div>
  </div>
</div>

<% end %>

app/views/general_users/users/show.html.erb
<!--一般マイページ-->
<div class="container">
  <div class="profile-wrap">
    <div class="row">
      <div class="col-md-4 text-center">
        <%= attachment_image_tag @general_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", class: "round-img" %>
      </div>
      <div class="col-md-8">
        <div class="row">
          <h1><%= @general_user.name %></h1>
          <%= link_to "プロフィール編集", edit_general_users_users_path, class: "btn btn-outline-secondary fas fa-user-cog edit-profile-btn" %>
        　<button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-cogs"></i></button>
        　 <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">設定</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
              <div class="list-group text-center">
                <%= link_to "ログアウト", destroy_farmer_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
                <%= link_to "退会する", unsubscribe_general_users_users_path(@general_user), class: "list-group-item list-group-item-action" %>
                <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
              </div>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <table class="table">
      <thead class="table-success">
        <tr>
          <th>農業体験依頼日</th>
          <th>主催者</th>
          <th>農業体験名</th>
          <th>農業体験日</th>
          <th>参加費</th>
          <th>連絡先</th>
        </tr>
      </thead>

    <tbody>
      <% @joins.each do |join| %>
      <tr>

        <th scope="row"><%= join.created_at.strftime('%Y/%m/%d') %></th>

        <th><%= join.event.farmer_user.name %></th>
        <th>
          <%= link_to general_users_event_path(join.event) do %>
          <%= join.event.title %>
         <% end %>
        </th>
        <th><%= join.event.event_date %></th>
        <th><%= join.event.price %>円</th>
        <th><%= mail_to join.event.farmer_user.email %></th>
      </tr>
    </tbody>
     <% end %>
  </table>

  </div>

</div>

app/views/general_users/users/unsubscribe.html.erb
<div class="container">
  <div class="row">
    <div class="card bg-light mb-3" style="max-width: 40rem;">
      <div class="card-header"><h4 class="text-center">本当に退会しますか?</h4></div>
      <div class="card-body">
        <p class="card-text"><i class="fas fa-exclamation-circle"></i>退会手続きをされますと、全てのサービスがご利用いただけなくなります。<br>
          再度ご利用をいただく場合には、新規登録のお手続きが必要になります。<br>
           本当に退会してよろしいですか？</p>

        <p class="card-text"><%= link_to "退会しない", general_users_users_path, class: "btn btn-primary" %><%= link_to "退会する", withdraw_general_users_users_path, method: :PATCH, data: { confirm: '退会しますか？' }, class: "btn btn-danger ml-4" %></p>
      </div>
    </div>
  </div>
</div>