config/routes.rb
Rails.application.routes.draw do

  # トップページ
  root to: 'home#index'
  # アバウトページ
  get 'home/about'
  # ユーザ選択ページ
  get 'home/choice'
  get 'home/choice_login'

    # 一般ユーザー
  devise_for :general_users, controllers: {
    sessions: 'general_users/sessions',
    passwords: 'general_users/passwords',
    registrations: 'general_users/registrations'
  }

  # 農家ユーザー
  devise_for :farmer_users, controllers: {
    sessions: 'farmer_users/sessions',
    passwords: 'farmer_users/passwords',
    registrations: 'farmer_users/registrations'
  }



# 一般ユーザー
  namespace :general_users do
    resources :customers, only: [:show]
    resource :users, only: [:show, :edit, :update] do
    collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
    #joinは、イベントに対して参加フォームを送信する。joinは、に結びつくためネスト（親子関係）する
    resources :events, only: [:index, :show] do
       get 'search', on: :collection
      resources :joins, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        post 'back'
        get 'complete'

      end
    end
  end

  #コメントは、投稿画像に対してコメントされる。post_commentsは、postに結びつくためネスト（親子関係）する
    resources :posts, only: [:index, :show] do
     resources :post_comments, only: [:create, :destroy]
    end

  end

  #農家ユーザー
  namespace :farmer_users do
    resources :customers, only: [:show]

    resource :users, only: [:show, :edit, :update] do
    collection do
      get 'unsubscribe'
      patch 'withdraw'
      end
    end

    #joinは、イベントに対して参加フォームを送信する。joinは、に結びつくためネスト（親子関係）する
    resources :events, only: [:new, :create, :index, :show, :destroy] do
      get 'search', on: :collection

      collection do
        get 'confirm'
      # post 'update'
      end
     resources :joins, only: [:new, :create, :index] do
     # 7つ以外のアクションがある時は，collection(idなし)とmember(id含む)を使って指定する。
      collection do
        post 'confirm'
        post 'back'
        get 'complete'
        # get 'show'
        end
      end
   end

    #コメントは、投稿画像に対してコメントする。このため、post_commentsは、postに結びつくためネスト（親子関係）する
    resources :posts, only: [:create, :index, :show, :destroy] do
     resources :post_comments, only: [:create, :destroy]
    end


  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  # farmeruserモデルを関連づける
   belongs_to :farmer_user

   has_many :joins, dependent: :destroy
   has_many :join_details, dependent: :destroy


   # 画像
   attachment :event_image

   validates :event_image, presence: true
   validates :title, presence: true
   validates :introduction, presence: true
   validates :price, presence: true
   validates :event_date, presence: true
   validates :event_place, presence: true

   def self.search(keyword)
    # where(["title like? OR introduction like? OR event_place like?", "%#{keyword}%", "%#{keyword}%"," %#{keyword}%"]).   なぜかevent_placeだけ検索できない
    where(['title LIKE(?) OR introduction LIKE(?) OR event_place LIKE(?)', "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
   end

 enum response_status: { outstanding: 0, in_progress: 1, closed: 2 }
end

app/models/farmer_user.rb
class FarmerUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
          validates :name, presence: true

          #Postモデルと関連づける
          has_many :posts, dependent: :destroy
          # eventモデルと関連づける
          has_many :events, dependent: :destroy

          # Post_commentモデルと関連づける
          has_many :post_comments, dependent: :destroy

          has_many :joins, dependent: :destroy


          # refileを使って、画像投稿ができるようにする
           attachment :profile_image
end

app/models/general_user.rb
class GeneralUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         validates :name, presence: true
        # has_many :posts, dependent: :destroy

         # Post_commentモデルと関連づける
         has_many :post_comments, dependent: :destroy

         has_many :joins, dependent: :destroy

         # refileを使って、画像投稿ができるようにする
           attachment :profile_image

end

app/models/join.rb
class Join < ApplicationRecord

  belongs_to :farmer_user, optional: true
  belongs_to :general_user, optional: true
  belongs_to :event, optional: true
  has_many :join_details, dependent: :destroy

   validates :email, :people, :name, presence: true
end

app/models/join_detail.rb
class JoinDetail < ApplicationRecord
  belongs_to :join, optional: true
  belongs_to :event, optional: true
  # enum response_status: { outstanding: 0, in_progress: 1, closed: 2 }
end

app/models/post.rb
class Post < ApplicationRecord

  # # farmeruserモデルを関連づける
   belongs_to :farmer_user

   # belongs_to :general_user, optional: true
   # 画像
   attachment :image
   # Post_commentモデルと関連づける
    has_many :post_comments, dependent: :destroy


   # バリデーションの設定
   validates :image, presence: true
   validates :title, presence: true
   validates :introduction, presence: true

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

   belongs_to :farmer_user, optional: true
 # Rails 5.1から関連付けが存在しない場合、belongs_toはデフォルトで検証エラーをトリガーします。
   belongs_to :general_user, optional: true
   belongs_to :post
   
   validates :comment, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?



   def after_sign_in_path_for(resource)
     case resource
     when FarmerUser
        farmer_users_users_path
     when GeneralUser
        general_users_users_path
     end
   end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

  def choice
  end

  def choice_login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farmer_users/customers_helper.rb
module FarmerUsers::CustomersHelper
end

app/helpers/farmer_users/events_helper.rb
module FarmerUsers::EventsHelper
end

app/helpers/farmer_users/joins_helper.rb
module FarmerUsers::JoinsHelper
end

app/helpers/farmer_users/posts_helper.rb
module FarmerUsers::PostsHelper
end

app/helpers/farmer_users/users_helper.rb
module FarmerUsers::UsersHelper
end

app/helpers/general_users/customers_helper.rb
module GeneralUsers::CustomersHelper
end

app/helpers/general_users/events_helper.rb
module GeneralUsers::EventsHelper
end

app/helpers/general_users/joins_helper.rb
module GeneralUsers::JoinsHelper
end

app/helpers/general_users/posts_helper.rb
module GeneralUsers::PostsHelper
end

app/helpers/general_users/users_helper.rb
module GeneralUsers::UsersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="containera about-top">
  <h4>With farmers</h4>
  <p>~若い世代に日本農業の「素晴らしさ」「ありがたさ」を~</p>



<div class="container py-3 px-md-5 p-5">
  <div class="row">
   <div class="d-flex justify-content-around ">
    <div class="about-title-features p-5">
     <h3 class="about-title"><strong>農業体験</strong></h3>
           <p class="text-success">農家の方が募集している農業を体験できる！！</p>
           <p class="text-success">使い方によっては，農家の方同士で助け合うことも可能！</p>

     </div>
     <div class="about-title-features p-5">
     <h3 class="about-title"><strong>農業日記</strong></h3>
           <p class="text-success">農家の方は日々の農業を日記として残すことができ，また，他のユーザーの方は投稿にコメントができる！</p>

     </div>
     <!--<div class="about-title-features p-5">-->
     <!--<h3 class="about-title"><strong>簡単登録</strong></h3>-->
     <!--      <p>簡単かつ無料で登録できる！</p>-->
     <!--</div>-->
    </div>
   </div>
  </div>
</div>









<!--<div class="about-green-contaner">-->
<!-- <div class="card devise-card">-->
<!--  <div class="form-wrap">-->
<!--   <div class="form-group text-center">-->
<!--    <h1 class="about-title mb-2"><strong>簡単登録!!</strong></h1>-->
<!--    <p class="text-secondary">登録はユーザー名，メールアドレス，パスワードのみ</>-->
<!--    <p class="text-secondary"><strong>完全無料</strong>です!!</p>-->
<!--   </div>-->
<!--  </div>-->
<!-- </div>-->
<!--  <div class="card devise-card">-->
<!--  <div class="form-wrap">-->
<!--   <div class="form-group text-center">-->
<!--    <h1 class="about-title mb-2"><strong>農業体験</strong></h1>-->
<!--    <p class="text-secondary">どちらのユーザーで<strong>ログイン</strong>しますか?</p>-->
<!--   </div>-->
<!--  </div>-->
<!-- </div>-->
<!--</div>-->

app/views/home/choice.html.erb
<div class="green-contaner">
 <div class="card devise-card">
  <div class="form-wrap">
   <div class="form-group text-center">
    <h1 class="choicce mb-2">With Farmers</h1>
    <p class="text-secondary">どちらのユーザーで<strong>新規登録</strong>しますか?</p>
    <%= link_to "農家ユーザー新規登録", new_farmer_user_registration_path, class: 'btn btn-success' %>
    <%= link_to "一般ユーザー新規登録", new_general_user_registration_path, class: 'btn btn-info' %>
    <!--<p class="text-secondary p-3">農家ユーザーは,農家の日常を投稿できたり，<br>農業体験を募集することができます。</p>-->
    <!--<p class="text-secondary">一般ユーザは，興味のある農業体験に応募できます。</p>-->
     <p class="devise-link p-3">
        アカウントをお持ちですか？
        <%= link_to "ログインする", home_choice_login_path %>
      </p>
   </div>
  </div>
 </div>
</div>

app/views/home/choice_login.html.erb
<div class="green-contaner">
 <div class="card devise-card">
  <div class="form-wrap">
   <div class="form-group text-center">
    <h1 class="choicce mb-2">With Farmers</h1>
    <p class="text-secondary">どちらのユーザーで<strong>ログイン</strong>しますか?</p>
    <%= link_to "農家ユーザーログイン", new_farmer_user_session_path, class: 'btn btn-success' %>
    <%= link_to "一般ユーザーログイン", new_general_user_session_path, class: 'btn btn-info' %>
    <!--<p class="text-secondary p-3">農家ユーザーは,農家の日常を投稿できたり，<br>農業体験を募集することができます。</p>-->
    <!--<p class="text-secondary">一般ユーザは，興味のある農業体験に応募できます。</p>-->
     <p class="devise-link p-3">
        アカウントをお持ちでないですか？
        <%= link_to "登録する", home_choice_path %>
      </p>
   </div>
  </div>
 </div>
</div>

app/views/home/index.html.erb
<div class="cover">
  <div class="text-center">
    <h1 class="title mb-2">With Farmers</h1>
     <p class="sub-title">〜農と人を繋ぐ〜</p>
      <% if farmer_user_signed_in? %>
      <div class="top-new-btn mt-3 mx-auto">
        <%= link_to 'マイページへGO!', farmer_users_users_path, class: 'press-down text-decoration-none' %>
      </div>
    <% elsif general_user_signed_in? %>
      <div class="top-new-btn mt-3 mx-auto">
        <%= link_to 'マイページへGO!', farmer_users_users_path, class: 'press-down text-decoration-none' %>
      </div>
    <% else %>
      <div class="top-new-btn mt-5 mx-auto">
        <%= link_to 'さっそく登録する！！', home_choice_path, class: 'press-down text-decoration-none' %>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="way pt-5">
    <h3 class="way-one"><i class="fas fa-bookmark"></i> <span class="title-color">With Farmers</span>の利用方法</h3>
    <p class="way-text"><span class="title-color">With Farmers</span>の基本的な使い方を簡単にご紹介！！</p>

    <div class="row way-about">
      <div class="way-imageleft col-10">
         <p class="way-one"><i class="fas fa-check"></i>気になる投稿や農業体験を探す</p>
         <p class="way-one"><i class="fas fa-check"></i>気になる投稿にはコメントをして農家の方と繋がろう！</p>
         <p class="way-one"><i class="fas fa-check"></i>気になる農業体験にはリクエストを送ろう！<br>
         <div class="way-two"><i class="fas fa-envelope-square"></i>リクエストの際にメールアドレスを入力していただきます。農家の方から詳細が送信されますのでご確認をお願いいたします。</div></p>
      </div>
    </div>
  </div>
</div>


<!--<div class="main-container">-->
<!--  <div class=" col-sm-10 mx-2 mx-sm-auto text-center  px-0 my-5">-->
<!--    <h1 class="top-page"><strong>With Farmers</strong></h1>-->
<!--    <h4 class="top-page"><p>〜農と人を繋ぐ〜</p></h4>-->
<!--    <div class="row">-->
      <!--<p class="ml-3"><a class="btn btn-info" href="/users/sign_in">Log in</a></p>-->
      <!--<p class="ml-3"><a class="btn btn-success" href="/users/sign_up">Sign Up</a></p>-->
<!--  </div>-->
<!-- </div>-->
<!--</div>-->