config/routes.rb
Rails.application.routes.draw do

  # トップページ
  root to: 'home#index'
  # アバウトページ
  get 'home/about'
  # ユーザ選択ページ
  get 'home/choice'
  get 'home/choice_login'

    # 一般ユーザー
  devise_for :general_users, controllers: {
    sessions: 'general_users/sessions',
    passwords: 'general_users/passwords',
    registrations: 'general_users/registrations'
  }

  # 農家ユーザー
  devise_for :farmer_users, controllers: {
    sessions: 'farmer_users/sessions',
    passwords: 'farmer_users/passwords',
    registrations: 'farmer_users/registrations'
  }



# 一般ユーザー
  namespace :general_users do
    resources :customers, only: [:show]
    resource :users, only: [:show, :edit, :update] do
    collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
    #joinは、イベントに対して参加フォームを送信する。joinは、に結びつくためネスト（親子関係）する
    resources :events, only: [:index, :show] do
       get 'search', on: :collection
      resources :joins, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        post 'back'
        get 'complete'

      end
    end
  end

  #コメントは、投稿画像に対してコメントされる。post_commentsは、postに結びつくためネスト（親子関係）する
    resources :posts, only: [:index, :show] do
     resources :post_comments, only: [:create, :destroy]
    end

  end

  #農家ユーザー
  namespace :farmer_users do
    resources :customers, only: [:show]

    resource :users, only: [:show, :edit, :update] do
    collection do
      get 'unsubscribe'
      patch 'withdraw'
      end
    end

    #joinは、イベントに対して参加フォームを送信する。joinは、に結びつくためネスト（親子関係）する
    resources :events, only: [:new, :create, :index, :show, :destroy] do
      get 'search', on: :collection

      collection do
        get 'confirm'
      # post 'update'
      end
     resources :joins, only: [:new, :create, :index] do
     # 7つ以外のアクションがある時は，collection(idなし)とmember(id含む)を使って指定する。
      collection do
        post 'confirm'
        post 'back'
        get 'complete'
        # get 'show'
        end
      end
   end

    #コメントは、投稿画像に対してコメントする。このため、post_commentsは、postに結びつくためネスト（親子関係）する
    resources :posts, only: [:create, :index, :show, :destroy] do
     resources :post_comments, only: [:create, :destroy]
    end


  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/farmer_user.rb
class FarmerUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
          validates :name, presence: true

          #Postモデルと関連づける
          has_many :posts, dependent: :destroy
          # eventモデルと関連づける
          has_many :events, dependent: :destroy

          # Post_commentモデルと関連づける
          has_many :post_comments, dependent: :destroy

          has_many :joins, dependent: :destroy


          # refileを使って、画像投稿ができるようにする
           attachment :profile_image
end

app/models/post.rb
class Post < ApplicationRecord

  # # farmeruserモデルを関連づける
   belongs_to :farmer_user

   # belongs_to :general_user, optional: true
   # 画像
   attachment :image
   # Post_commentモデルと関連づける
    has_many :post_comments, dependent: :destroy


   # バリデーションの設定
   validates :image, presence: true
   validates :title, presence: true
   validates :introduction, presence: true

end

app/controllers/farmer_users/confirmations_controller.rb
# frozen_string_literal: true

class FarmerUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/farmer_users/customers_controller.rb
class FarmerUsers::CustomersController < ApplicationController
before_action :authenticate_farmer_user!
  def show
    @farmer_user = FarmerUser.find(params[:id])
    @posts = @farmer_user.posts.all.order(created_at: :desc)
    @events = @farmer_user.events.all.order(created_at: :desc)

  end

end

app/controllers/farmer_users/events_controller.rb
class FarmerUsers::EventsController < ApplicationController

before_action :authenticate_farmer_user!
  # def new
  # end

  def index
    @event = Event.new
    @events = Event.all.order(created_at: :desc)
  end

  def search
    @event = Event.new
    @events = Event.search(params[:keyword])
    @keyword = params[:keyword]
    render "index"
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    @event.farmer_user_id = current_farmer_user.id
    if @event.save
      redirect_to farmer_users_events_path
    else
      @events = Event.all.order(created_at: :desc)
      render action: :index
    end

  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to farmer_users_events_path
  end

  def confirm
    @farmer_user = current_farmer_user
    @general_user = current_general_user
    @events = @farmer_user.events.all
    # @joins = Join.where(event_id: )
    @joins = Join.all

  end




  # def updated
  # if @event.update(event_params)
  #     redirect_to confirm_farmer_users_events, notice: "対応ステータスを更新しました"
  # else
  #     render :confirm, alert: "対応ステータスを更新できませんでした"
  # end
  # end

  private
  def event_params
    params.require(:event).permit(:title, :event_image, :introduction, :event_date, :event_place, :price, :response_status)
  end

end

app/controllers/farmer_users/joins_controller.rb
class FarmerUsers::JoinsController < ApplicationController
  before_action :authenticate_farmer_user!

  def new
    @event = Event.find(params[:event_id])
    @join = Join.new
  end
  # newアクションから入力内容を受け取り、
   # 送信ボタンを押されたらcreateアクションを実行します
  def confirm
    @event = Event.find(params[:event_id])
    @join = Join.new(join_params)
    @join.farmer_user_id = current_farmer_user.id
  end

  def back
    @event = Event.find(params[:event_id])
    @join = Join.new(join_params)
    render :new
  end

  def create
    @event = Event.find(params[:event_id])
    @join = current_farmer_user.joins.new(join_params)
    @join.event_id = @event.id
    if @join.save
     redirect_to complete_farmer_users_event_joins_path
    else
     render :new
    end
  end

  def complete
  end

  def index
    @farmer_user = current_farmer_user
    @joins = @farmer_user.joins.all.order(created_at: :desc)
  end

  # def show
  #   @join = Join.find(params[:id])
  #   if @event.join_id = current_farmer_user.id
  #   else
  #       @event.join_id = current_general_userd.id
  #   end
  # end

  def join_params
    params.require(:join).permit(:farmer_user_id, :email, :phone, :people, :name, :memo)
  end

end

app/controllers/farmer_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class FarmerUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/farmer_users/passwords_controller.rb
# frozen_string_literal: true

class FarmerUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/farmer_users/post_comments_controller.rb
class FarmerUsers::PostCommentsController < ApplicationController
  before_action :authenticate_farmer_user!

  def create
    post = Post.find(params[:post_id])
    # comment = current_farmer_user.post_comments.new(post_comment_params)
    comment = PostComment.new(post_comment_params)
    
    if current_farmer_user
    comment.farmer_user_id = current_farmer_user.id
    else
    comment.general_user_id = current_general_user.id
    end
    comment.post_id = post.id
    comment.save
    redirect_to farmer_users_post_path(params[:post_id])
  end

  def destroy
    PostComment.find_by(id: params[:id]).destroy
    redirect_to farmer_users_post_path(params[:post_id])
  end

  private
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/farmer_users/posts_controller.rb
class FarmerUsers::PostsController < ApplicationController
  before_action :authenticate_farmer_user!
  def new

  end

  def create
    @post = Post.new(post_params)
    @post.farmer_user_id = current_farmer_user.id
    if @post.save
      redirect_to farmer_users_posts_path
    else
      @posts = Post.all.order(created_at: :desc)
      render action: :index
    end
  end

  def index
    @post = Post.new
    @posts = Post.all.order(created_at: :desc)

  end

  def show
    @post = Post.find(params[:id])
    # @post_comments = @post.comments
    # コメントのインスタンス変数記述
    @post_comment = PostComment.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to farmer_users_posts_path
  end


  private
  def post_params
    params.require(:post).permit(:title, :image, :introduction)
  end
end

app/controllers/farmer_users/registrations_controller.rb
# frozen_string_literal: true

class FarmerUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/farmer_users/sessions_controller.rb
# frozen_string_literal: true

class FarmerUsers::SessionsController < Devise::SessionsController
  before_action :reject_farmer_user, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected
  def reject_farmer_user
    @farmer_user = FarmerUser.find_by(email: params[:farmer_user][:email].downcase)
    if @farmer_user
    if (@farmer_user.valid_password?(params[:farmer_user][:password]) && !@farmer_user.is_active)
      flash[:notice] = "退会済みです。新たにアカウントを作成してください。"
      redirect_to new_farmer_user_registration_path
    end
    end
  end
end

app/controllers/farmer_users/unlocks_controller.rb
# frozen_string_literal: true

class FarmerUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/farmer_users/users_controller.rb
class FarmerUsers::UsersController < ApplicationController
  before_action :authenticate_farmer_user!

  def show
    @farmer_user = current_farmer_user
    @posts = @farmer_user.posts.all.order(created_at: :desc)
    @events = @farmer_user.events.all.order(created_at: :desc)
    @joins = @farmer_user.joins.all.order(created_at: :desc)
    @join_lists = Join.all.order(created_at: :desc)
    @event_lists = @farmer_user.events.all.order(created_at: :desc)

  end

  def edit
    @farmer_user = current_farmer_user
  end

  def update
    @farmer_user = current_farmer_user
    if @farmer_user.update(farmer_user_params)
      flash[:notice] = '情報を変更しました。'
      redirect_to farmer_users_users_path(current_farmer_user)
    else
      render :edit
    end
  end

  def statusupdate
    # if @event.update(event_params)
  #     redirect_to confirm_farmer_users_events, notice: "対応ステータスを更新しました"
  # else
  #     render :confirm, alert: "対応ステータスを更新できませんでした"
  # end

  end

  # 退会ページ
  def unsubscribe
     @farmer_user = current_farmer_user
  end

  def withdraw
    @farmer_user = current_farmer_user
    @farmer_user.destroy
    flash[:notice] = "ありがとうございました。又のご利用を心よりお待ちしております。"
    redirect_to root_path
  end

   def farmer_user_params
     	params.require(:farmer_user).permit(:name, :email, :profile_image)
   end
end

app/controllers/general_users/posts_controller.rb
class GeneralUsers::PostsController < ApplicationController

  before_action :authenticate_general_user!
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show

    @post = Post.find(params[:id])
    @post_comment = PostComment.new #コメントのインスタンス変数を記述
  end

end

app/helpers/farmer_users/customers_helper.rb
module FarmerUsers::CustomersHelper
end

app/helpers/farmer_users/events_helper.rb
module FarmerUsers::EventsHelper
end

app/helpers/farmer_users/joins_helper.rb
module FarmerUsers::JoinsHelper
end

app/helpers/farmer_users/post_comments_helper.rb
module FarmerUsers::PostCommentsHelper
end

app/helpers/farmer_users/posts_helper.rb
module FarmerUsers::PostsHelper
end

app/views/farmer_users/posts/index.html.erb
<div class="container">
  <!--新規投稿-->
 <div class="d-flex justify-content-center">
    <% if @post.errors.any? %>
  　<%= @post.errors.count %>件のエラーが発生しました。入力を確認してください。
  <% end %>
  <h3><button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-plus btn btn-success"></i></button></h3>
 </div>

 <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">農業日記投稿</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="list-group text-center">
          <%= form_with model: @post, url: farmer_users_posts_path, local:true do |f| %>
           <div class="card-title">
            <%= f.attachment_field :image %>
           </div>
           <div class="card-title">
             <label for="book_opinion">タイトル</label>
             <%= f.text_field :title, class:"form-control" %>
           </div>
           <div class="card-title">
            <label for="book_opinion">日記</label>
            <%= f.text_area :introduction , class:"form-control" %>
           </div>
           <div class="card-title">
            <%= f.submit '投稿', class: "btn btn-success" %>
           </div>
         </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

<% @posts.each do |post| %>
<div class="contaner">
          <!--農業日記一覧-->

<div class="card w-50 mx-auto mt-4 shadow-lg">
  <div class="card-wrap">
    <div class="d-flex bd-highlight">
      <div class="p-2 flex-grow-1 bd-highlight">
        <%= link_to farmer_users_customer_path(post.farmer_user) do %>
        <%= attachment_image_tag post.farmer_user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", class: "circle" %><%= post.farmer_user.name %>
        <% end %>
       </div>
      <div class="p-2 bd-highlight">
      <i class="far fa-clock"><%= post.created_at.strftime('%Y/%m/%d') %></i>
      </div>
      </div>
    <%= link_to farmer_users_post_path(post.id) do %>
    <%= attachment_image_tag post, :image, class:"card-img-top"; %>
    <% end %>

      <div class="card-body">
        <div class="row">
          <div class="col-10">
            <p card="card-title">
             <strong><i class="far fa-flag"></i><span><%= post.title %></span></strong>
            </p>
            <div class="d-flex bd-highlight">
            <div class="p-2 flex-grow-1 bd-highlight">
            <p class="card-text"><%= post.introduction %>
            </div>
            <div class="p-2 bd-highlight">
            <%=link_to farmer_users_post_path(post.id) do %>
            <h3><strong><i class="fas fa-comments"></i></strong></h3>
            <% end %>
            </div>
            </div>
            </p>
          </div>
        </div>
    </div>
   </div>
  </div>
  <% end %>
</div>

app/views/farmer_users/posts/new.html.erb
<!-- 農業を投稿するページ-->
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">農業日記</h5>
      <div class="form-body p-4">

        

      <%= form_with model: @post, url: farmer_users_posts_path, local:true do |f| %>
      <h6>画像<i class="fas fa-image"></i></h6>
      <%= f.attachment_field :image %>
      <h6>タイトル</h6>
      <%= f.text_field :title %>
      <h6>日記</h6>
      <%= f.text_area :introduction %>
      <%= f.submit '投稿' %>
     <% end %>
     </div>
    </div>
  </div>

</div>

app/views/farmer_users/posts/show.html.erb
<!--投稿詳細ページ-->
<div class="card w-50 mx-auto mt-4 shadow-lg">
  <div class="card-wrap">
    <div class="d-flex bd-highlight">
      <div class="p-2 flex-grow-1 bd-highlight">
        <%= link_to farmer_users_customer_path(@post.farmer_user) do %>
         <%= attachment_image_tag @post.farmer_user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", class: "circle" %><%= @post.farmer_user.name %>
       <% end %>
      </div>
       <div class="p-2 bd-highlight">
         <i class="far fa-clock"><%= @post.created_at.strftime('%Y/%m/%d') %></i>
       </div>
       <div class="p-2 bd-highlight">
         <% if @post.farmer_user == current_farmer_user %>
          <%= link_to farmer_users_post_path(@post), method: :delete do %>
          <h3 class="text-dark"><i class="far fa-trash-alt"></i></h3>
          <% end %>
         <% end %>
       </div>
    </div>
    <%= attachment_image_tag @post, :image, class:"card-img-top"; %>
    <div class="card-body">
      <div class="row">
        <div class="col-10">
          <p card="card-title">
            <strong><i class="far fa-flag"></i><span><%= @post.title %></span></strong>
          </p>
          <p class="card-text"><%= @post.introduction %></p>
        </div>
      </div>
      <hr>
      <div class="comments card-text">
        <h6 class="mt-3"><%= @post.post_comments.count %>件のコメント</h6>
        <div class="new-comment card-text">
          <%= form_with(model:[@post, @post_comment], url: farmer_users_post_post_comments_path(@post), local: true) do |f| %>
          <div class="input-group mb-3">
          <!--<input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="button-addon2">-->
          <%= f.text_area :comment, class:"form-control", placeholder: "コメントを投稿" %>
          <div class="input-group-append">
            <%= f.submit "コメントする", class:"btn btn-outline-secondary", id: "button-addon2" %>
            <!--<button class="btn btn-outline-secondary" type="button" id="button-addon2"></button>-->
          </div>
        </div>
          <% end %>

       </div>
        <% @post.post_comments.each do |post_comment| %>
        <div class="media border mb-1">
          <% if post_comment.farmer_user %>
          <div>
           <%= attachment_image_tag post_comment.farmer_user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", class: "circle" %><br>
        　<div class="ml-2 text-muted"><i class="far fa-user"></i><%= post_comment.farmer_user.name %></div>
        </div>
          <% else %>
          <div>
           <%= attachment_image_tag post_comment.general_user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", class: "circle" %><br>
           <div class="ml-2 text-muted"><i class="far fa-user"></i><%= post_comment.general_user.name %></div>
          </div>
          <% end %>
          <div class="media-body ml-4 p-1">
            <div class="d-flex bd-highlight">
              <div class="p-2 flex-grow-1 bd-highlight"><%= post_comment.comment %></div>
              <div class="p-2 bd-highlight">
                 <i class="far fa-clock"><%= post_comment.created_at.strftime('%Y/%m/%d') %></i><br>
                <% if post_comment.farmer_user == current_farmer_user %>
                <%= link_to farmer_users_post_post_comment_path(post_comment.post, post_comment), method: :delete do %>
                <h3 class="text-dark ml-2 p-2"><i class="far fa-trash-alt"></i></h3>
                <% end %>
              <% end %>
              </div>
            </div>

           </div>
        </div>
         <% end %>
      </div>


  </div>
</div>