config/routes.rb
Rails.application.routes.draw do

  # トップページ
  root to: 'home#index'
  # アバウトページ
  get 'home/about'
  # ユーザ選択ページ
  get 'home/choice'
  get 'home/choice_login'

    # 一般ユーザー
  devise_for :general_users, controllers: {
    sessions: 'general_users/sessions',
    passwords: 'general_users/passwords',
    registrations: 'general_users/registrations'
  }

  # 農家ユーザー
  devise_for :farmer_users, controllers: {
    sessions: 'farmer_users/sessions',
    passwords: 'farmer_users/passwords',
    registrations: 'farmer_users/registrations'
  }



# 一般ユーザー
  namespace :general_users do
    resources :customers, only: [:show]
    resource :users, only: [:show, :edit, :update] do
    collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
    #joinは、イベントに対して参加フォームを送信する。joinは、に結びつくためネスト（親子関係）する
    resources :events, only: [:index, :show] do
       get 'search', on: :collection
      resources :joins, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        post 'back'
        get 'complete'

      end
    end
  end

  #コメントは、投稿画像に対してコメントされる。post_commentsは、postに結びつくためネスト（親子関係）する
    resources :posts, only: [:index, :show] do
     resources :post_comments, only: [:create, :destroy]
    end

  end

  #農家ユーザー
  namespace :farmer_users do
    resources :customers, only: [:show]

    resource :users, only: [:show, :edit, :update] do
    collection do
      get 'unsubscribe'
      patch 'withdraw'
      end
    end

    #joinは、イベントに対して参加フォームを送信する。joinは、に結びつくためネスト（親子関係）する
    resources :events, only: [:new, :create, :index, :show, :destroy] do
      get 'search', on: :collection

      collection do
        get 'confirm'
      # post 'update'
      end
     resources :joins, only: [:new, :create, :index] do
     # 7つ以外のアクションがある時は，collection(idなし)とmember(id含む)を使って指定する。
      collection do
        post 'confirm'
        post 'back'
        get 'complete'
        # get 'show'
        end
      end
   end

    #コメントは、投稿画像に対してコメントする。このため、post_commentsは、postに結びつくためネスト（親子関係）する
    resources :posts, only: [:create, :index, :show, :destroy] do
     resources :post_comments, only: [:create, :destroy]
    end


  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  # farmeruserモデルを関連づける
   belongs_to :farmer_user

   has_many :joins, dependent: :destroy
   has_many :join_details, dependent: :destroy


   # 画像
   attachment :event_image

   validates :event_image, presence: true
   validates :title, presence: true
   validates :introduction, presence: true
   validates :price, presence: true
   validates :event_date, presence: true
   validates :event_place, presence: true

   def self.search(keyword)
    # where(["title like? OR introduction like? OR event_place like?", "%#{keyword}%", "%#{keyword}%"," %#{keyword}%"]).   なぜかevent_placeだけ検索できない
    where(['title LIKE(?) OR introduction LIKE(?) OR event_place LIKE(?)', "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
   end

 enum response_status: { outstanding: 0, in_progress: 1, closed: 2 }
end

app/models/farmer_user.rb
class FarmerUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
          validates :name, presence: true

          #Postモデルと関連づける
          has_many :posts, dependent: :destroy
          # eventモデルと関連づける
          has_many :events, dependent: :destroy

          # Post_commentモデルと関連づける
          has_many :post_comments, dependent: :destroy

          has_many :joins, dependent: :destroy


          # refileを使って、画像投稿ができるようにする
           attachment :profile_image
end

app/controllers/farmer_users/confirmations_controller.rb
# frozen_string_literal: true

class FarmerUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/farmer_users/customers_controller.rb
class FarmerUsers::CustomersController < ApplicationController
before_action :authenticate_farmer_user!
  def show
    @farmer_user = FarmerUser.find(params[:id])
    @posts = @farmer_user.posts.all.order(created_at: :desc)
    @events = @farmer_user.events.all.order(created_at: :desc)

  end

end

app/controllers/farmer_users/events_controller.rb
class FarmerUsers::EventsController < ApplicationController

before_action :authenticate_farmer_user!
  # def new
  # end

  def index
    @event = Event.new
    @events = Event.all.order(created_at: :desc)
  end

  def search
    @event = Event.new
    @events = Event.search(params[:keyword])
    @keyword = params[:keyword]
    render "index"
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    @event.farmer_user_id = current_farmer_user.id
    if @event.save
      redirect_to farmer_users_events_path
    else
      @events = Event.all.order(created_at: :desc)
      render action: :index
    end

  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to farmer_users_events_path
  end

  def confirm
    @farmer_user = current_farmer_user
    @general_user = current_general_user
    @events = @farmer_user.events.all
    # @joins = Join.where(event_id: )
    @joins = Join.all

  end




  # def updated
  # if @event.update(event_params)
  #     redirect_to confirm_farmer_users_events, notice: "対応ステータスを更新しました"
  # else
  #     render :confirm, alert: "対応ステータスを更新できませんでした"
  # end
  # end

  private
  def event_params
    params.require(:event).permit(:title, :event_image, :introduction, :event_date, :event_place, :price, :response_status)
  end

end

app/controllers/farmer_users/joins_controller.rb
class FarmerUsers::JoinsController < ApplicationController
  before_action :authenticate_farmer_user!

  def new
    @event = Event.find(params[:event_id])
    @join = Join.new
  end
  # newアクションから入力内容を受け取り、
   # 送信ボタンを押されたらcreateアクションを実行します
  def confirm
    @event = Event.find(params[:event_id])
    @join = Join.new(join_params)
    @join.farmer_user_id = current_farmer_user.id
  end

  def back
    @event = Event.find(params[:event_id])
    @join = Join.new(join_params)
    render :new
  end

  def create
    @event = Event.find(params[:event_id])
    @join = current_farmer_user.joins.new(join_params)
    @join.event_id = @event.id
    if @join.save
     redirect_to complete_farmer_users_event_joins_path
    else
     render :new
    end
  end

  def complete
  end

  def index
    @farmer_user = current_farmer_user
    @joins = @farmer_user.joins.all.order(created_at: :desc)
  end

  # def show
  #   @join = Join.find(params[:id])
  #   if @event.join_id = current_farmer_user.id
  #   else
  #       @event.join_id = current_general_userd.id
  #   end
  # end

  def join_params
    params.require(:join).permit(:farmer_user_id, :email, :phone, :people, :name, :memo)
  end

end

app/controllers/farmer_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class FarmerUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/farmer_users/passwords_controller.rb
# frozen_string_literal: true

class FarmerUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/farmer_users/post_comments_controller.rb
class FarmerUsers::PostCommentsController < ApplicationController
  before_action :authenticate_farmer_user!

  def create
    post = Post.find(params[:post_id])
    # comment = current_farmer_user.post_comments.new(post_comment_params)
    comment = PostComment.new(post_comment_params)
    
    if current_farmer_user
    comment.farmer_user_id = current_farmer_user.id
    else
    comment.general_user_id = current_general_user.id
    end
    comment.post_id = post.id
    comment.save
    redirect_to farmer_users_post_path(params[:post_id])
  end

  def destroy
    PostComment.find_by(id: params[:id]).destroy
    redirect_to farmer_users_post_path(params[:post_id])
  end

  private
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/farmer_users/posts_controller.rb
class FarmerUsers::PostsController < ApplicationController
  before_action :authenticate_farmer_user!
  def new

  end

  def create
    @post = Post.new(post_params)
    @post.farmer_user_id = current_farmer_user.id
    if @post.save
      redirect_to farmer_users_posts_path
    else
      @posts = Post.all.order(created_at: :desc)
      render action: :index
    end
  end

  def index
    @post = Post.new
    @posts = Post.all.order(created_at: :desc)

  end

  def show
    @post = Post.find(params[:id])
    # @post_comments = @post.comments
    # コメントのインスタンス変数記述
    @post_comment = PostComment.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to farmer_users_posts_path
  end


  private
  def post_params
    params.require(:post).permit(:title, :image, :introduction)
  end
end

app/controllers/farmer_users/registrations_controller.rb
# frozen_string_literal: true

class FarmerUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/farmer_users/sessions_controller.rb
# frozen_string_literal: true

class FarmerUsers::SessionsController < Devise::SessionsController
  before_action :reject_farmer_user, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected
  def reject_farmer_user
    @farmer_user = FarmerUser.find_by(email: params[:farmer_user][:email].downcase)
    if @farmer_user
    if (@farmer_user.valid_password?(params[:farmer_user][:password]) && !@farmer_user.is_active)
      flash[:notice] = "退会済みです。新たにアカウントを作成してください。"
      redirect_to new_farmer_user_registration_path
    end
    end
  end
end

app/controllers/farmer_users/unlocks_controller.rb
# frozen_string_literal: true

class FarmerUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/farmer_users/users_controller.rb
class FarmerUsers::UsersController < ApplicationController
  before_action :authenticate_farmer_user!

  def show
    @farmer_user = current_farmer_user
    @posts = @farmer_user.posts.all.order(created_at: :desc)
    @events = @farmer_user.events.all.order(created_at: :desc)
    @joins = @farmer_user.joins.all.order(created_at: :desc)
    @join_lists = Join.all.order(created_at: :desc)
    @event_lists = @farmer_user.events.all.order(created_at: :desc)

  end

  def edit
    @farmer_user = current_farmer_user
  end

  def update
    @farmer_user = current_farmer_user
    if @farmer_user.update(farmer_user_params)
      flash[:notice] = '情報を変更しました。'
      redirect_to farmer_users_users_path(current_farmer_user)
    else
      render :edit
    end
  end

  def statusupdate
    # if @event.update(event_params)
  #     redirect_to confirm_farmer_users_events, notice: "対応ステータスを更新しました"
  # else
  #     render :confirm, alert: "対応ステータスを更新できませんでした"
  # end

  end

  # 退会ページ
  def unsubscribe
     @farmer_user = current_farmer_user
  end

  def withdraw
    @farmer_user = current_farmer_user
    @farmer_user.destroy
    flash[:notice] = "ありがとうございました。又のご利用を心よりお待ちしております。"
    redirect_to root_path
  end

   def farmer_user_params
     	params.require(:farmer_user).permit(:name, :email, :profile_image)
   end
end

app/controllers/general_users/events_controller.rb
class GeneralUsers::EventsController < ApplicationController
  before_action :authenticate_general_user!
  def index
    @events = Event.all.order(created_at: :desc)
  end

  def show
    @event = Event.find(params[:id])
  end

  def search
    @events = Event.search(params[:keyword])
    @keyword = params[:keyword]
    render "index"
  end

end

app/helpers/farmer_users/customers_helper.rb
module FarmerUsers::CustomersHelper
end

app/helpers/farmer_users/events_helper.rb
module FarmerUsers::EventsHelper
end

app/helpers/farmer_users/joins_helper.rb
module FarmerUsers::JoinsHelper
end

app/helpers/farmer_users/post_comments_helper.rb
module FarmerUsers::PostCommentsHelper
end

app/helpers/farmer_users/posts_helper.rb
module FarmerUsers::PostsHelper
end

app/views/farmer_users/events/confirm.html.erb
<!--イベント参加者リスト確認ページ-->
<div class="container">
  <div class="row">
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th>農業体験名</th>
          <th>農業体験日</th>
          <th>体験希望者</th>
          <th>申込日</th>
          <th>メールアドレス</th>
          <th>電話番号</th>
          <th>参加人数</th>
          <th>備考（要望等）</th>
        </tr>
      </thead>


       <% @events.each do |event| %>
       <% @joins.where(event_id: event.id).each do |join| %>
        <body>
          <tr>
            <td><%= event.title %></td>
            <td><%= event.event_date %></td>
            <td><%= join.name %> </td>
            <td><%= join.created_at.to_s(:datetime_jp) %></td>
            <td><%= mail_to join.email %></td>
            <td><%= join.phone %></td>
            <td><%= join.people %>名</td>
            <td><%= join.memo %></td>
            <!--ステータス-->
            <!--%= form_with model: @event, url: farmer_users_events_path, local: true do |f| %>-->
            <!--<td>%= f.select :response_status, Event.response_statuses.keys.map {|k| [I18n.t("enums.event.response_status.#{k}"), k]} %></td>-->
            <!--<td>%= f.submit "変更" %></td>-->
            <!--% end %>-->

 <% end %>
 <% end %>

          </tr>
      </body>
    </table>
   </div>
  </div>
 <div>
</div>

app/views/farmer_users/events/index.html.erb
<!--農業体験一覧-->

<div class="container">
<%= form_with url: search_farmer_users_events_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, value: @keyword,placeholder:"キーワードを入力" %>
    <%= f.submit "検索", class: "btn btn-outline-secondary" %>
  <% end %>

 <div class="d-flex justify-content-center">
  <% if @event.errors.any? %>
  <%= @event.errors.count %>件のエラーが発生しました。入力を確認してください。
 <% end %>
  <h3><button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-plus btn btn-success"></i></button></h3>
 </div>

  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">農業体験投稿</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="list-group text-center">
          <%= form_with model: @event, url: farmer_users_events_path, local:true do |f| %>
           <div class="card-title">
            <%= f.attachment_field :event_image %>
           </div>
           <div class="card-title">
             <label for="book_opinion">農業体験名</label>
             <%= f.text_field :title, class:"form-control", placeholder:"ぶどう狩り🍇" %>
           </div>
           <div class="card-title">
            <label for="book_opinion">詳細</label>
            <%= f.text_area :introduction, class:"form-control", placeholder:"農業体験の詳細を記入してください。" %>
           </div>
           <div class="card-title">
            <label for="book_opinion">日程/時間</label>
            <%= f.text_field :event_date, class:"form-control", placeholder:"２０●●年●●月●●日/午前●●時から" %>
           </div>
           <div class="card-title">
            <label for="book_opinion">場所(都道府県・市町村名)</label>
            <%= f.text_field :event_place, class:"form-control", placeholder:"山梨県〇〇付近" %>
           </div>
           <div class="card-title">
            <label for="book_opinion">参加費（半角数字）</label>
            <%= f.text_field :price, class:"form-control", placeholder:"参加費がある場合は記入してください。" %>
            </div>
           <div class="card-title">
            <%= f.submit '投稿', class: "btn btn-success" %>
           </div>
         </div>
          <% end %>
      </div>
    </div>
  </div>
</div>


<!--<div class="container">-->

 <!--投稿一覧-->
 <% @events.each do |event| %>
 <div class="card w-50 mx-auto mt-4 shadow-lg">

  <div class="card-wrap">
   <div class="d-flex bd-highlight">
    <div class="p-2 flex-grow-1 bd-highlight">
     <!--プロフィール-->
     <%= link_to farmer_users_customer_path(event.farmer_user) do %>
      <%= attachment_image_tag event.farmer_user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", class: "circle" %><%= event.farmer_user.name %>
     <% end %>
    </div>
    <div class="p-2 bd-highlight">
     <i class="far fa-clock"><%= event.created_at.strftime('%Y/%m/%d') %></i>
    </div>
   </div>
   <%= link_to farmer_users_event_path(event.id) do %>
    <%= attachment_image_tag event, :event_image, class:"card-img-top"; %>
   <% end %>
   <div class="card-body">
    <div class="row">
     <div class="col-10">
      <p class="card-title">
       <strong><i class="far fa-flag"></i><span><%= event.title %></strong>
      </p>
      <div class="d-flex bd-highlight">
       <div class="p-2 flex-grow-1 bd-highlight"><p class="card-text"><%= event.introduction %></div></p>
      </div>
      <div class="p-2 flex-grow-1 bd-highlight"><p class="card-text"><i class="fas fa-location-arrow"></i><%= event.event_place %></div></p>
     </div>
    </div>
   </div>
  </div>
 </div>
 <% end %>
<!--</div>-->

app/views/farmer_users/events/new.html.erb
<!-- 農業を投稿するページ-->
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">農業体験！！</h5>
      <div class="form-body p-4">

        <!--ここからエラーメッセージ-->
        <% if @event.errors.any? %>
        <%= @event.errors.count %>件のエラーが発生しました。入力を確認してください。
        <% @event.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
        <% end %>
        <!--ここまで-->


      <%= form_with model: @event, url: farmer_users_events_path, local:true do |f| %>
      <h6>画像</h6>
      <%= f.attachment_field :event_image %>
      <h6>イベント名</h6>
      <%= f.text_field :title %>
      <h6>日時</h6>
      <%= f.text_field :event_date %>
      <h6>参加費</h6>
      ¥<%= f.text_field :price %>
      <h6>詳細内容</h6>
      <%= f.text_area :introduction %>

      <%= f.submit '投稿' %>
     <% end %>
     </div>
    </div>
  </div>

</div>

app/views/farmer_users/events/show.html.erb
<!--投稿詳細ページ-->
<div class="card w-50 mx-auto mt-4 shadow-lg">

  <div class="card-wrap">
    <div class="d-flex bd-highlight">
      <div class="p-2 flex-grow-1 bd-highlight">
        <%= link_to farmer_users_customer_path(@event.farmer_user) do %>
         <%= attachment_image_tag @event.farmer_user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", class: "circle" %><%= @event.farmer_user.name %>
        <% end %>
      </div>
      <div class="p-2 bd-highlight">
        <i class="far fa-clock"><%= @event.created_at.strftime('%Y/%m/%d') %></i>
      </div>
      <div class="p-2 bd-highlight">
         <% if @event.farmer_user == current_farmer_user %>
          <%= link_to farmer_users_event_path(@event), method: :delete do %>
          <h3 class="text-dark"><i class="far fa-trash-alt"></i></h3>
          <% end %>
         <% end %>
      </div>
    </div>
    <%= attachment_image_tag @event, :event_image, class: "card-img-top" %>
    <div class="card-body">
       <p class="card-title">
         <strong><i class="far fa-flag"></i><span><%= @event.title %></span></strong>
       </p>
       <p class="card-body">
         <%= @event.introduction %>
       </p>
       <h6 class="card-body p-3 border-top d-flex justify-content-center">
         <i class="fas fa-calendar-alt"></i><%= @event.event_date %>
       </h6>
       <h6 class="card-body p-3 border-top d-flex justify-content-center">
           <i class="fas fa-location-arrow"></i><%= @event.event_place %>
       </h6>
       <h6 class="card-body p-3 border-top border-bottom d-flex justify-content-center">
          <i class="fas fa-yen-sign"></i><%= @event.price %>円
        </h6>
        <%= link_to "参加リクエスト", new_farmer_users_event_join_path(@event), class: "btn btn-outline-primary d-flex justify-content-center" %>
        </div>
      </div>
    </div>
  </div>
</div>